name: ðŸ§ª Run Tests
on:
  workflow_call:

jobs:
  run-tests-2d:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chickensoft-games/setup-godot@v1
        name: ðŸ¤– Setup Godot
        with:
          version: 4.3.0
          use-dotnet: false
          include-templates: true
      - name: Run Unit Tests for 2D Build
        shell: sh
        run: |
          cargo test --all-targets --features="build2d,test" --no-default-features
      - name: Run Integration Tests for 2D Build
        shell: sh
        run: |
          return
          ./scripts/build-dev-2d.sh
          ls bin2d/addons/bin
          godot --headless --path ./bin2d test.tscn --quit-after 1000 > output.log 2>&1
          echo "---------------------"
          grep "ERROR:" output.log
          echo "---------------------"
          if grep -q "ERROR:" output.log; then
            echo "Error found in output"
            exit 1
          elif grep -q "Success" output.log; then
            echo "Test completed successfully"
          else
            echo "No success message found"
            exit 1
          fi

  run-tests-3d:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v1
        name: ðŸ¤– Setup Godot
        with:
          version: 4.3.0
          use-dotnet: false
          include-templates: true
      - name: Run Unit Tests for 3D Build
        shell: sh
        run: |
          cargo test --all-targets --features="build3d,test" --no-default-features
      - name: Run Integration Tests for 3D Build
        shell: sh
        run: |
          ./scripts/build-dev-3d.sh
          ls bin2d/addons/bin
          godot --headless --path ./bin3d test.tscn --quit-after 1000 > output.log 2>&1
          echo "---------------------"
          grep "ERROR:" output.log
          echo "---------------------"
          if grep -q "ERROR:" output.log; then
            echo "Error found in output"
            exit 1
          elif grep -q "Success" output.log; then
            echo "Test completed successfully"
          else
            echo "No success message found"
            exit 1
          fi
